# Generated by Django 5.0.6 on 2024-06-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pepper_type', models.CharField(max_length=255, verbose_name='Тип перца')),
                ('pepper_color', models.CharField(max_length=20, verbose_name='Цвет перца')),
                ('number_of_seeds', models.CharField(max_length=2, verbose_name='Число семян')),
                ('image', models.ImageField(upload_to='shop/images/', verbose_name='Изображение')),
                ('price_no_discount', models.IntegerField(verbose_name='Цена без скидки')),
                ('scoville_value', models.IntegerField(max_length=8, verbose_name='Шкала Сковилла')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
            ],
        ),
    ]
