# Generated by Django 5.0.6 on 2024-07-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения'),
        ),
    ]
